-- MySQL Script generated by MySQL Workbench
-- Tue Jun 26 11:16:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema homeinventorydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `homeinventorydb` ;

-- -----------------------------------------------------
-- Schema homeinventorydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homeinventorydb` DEFAULT CHARACTER SET latin1 ;
USE `homeinventorydb` ;

-- -----------------------------------------------------
-- Table `homeinventorydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeinventorydb`.`users` (
  `Username` VARCHAR(20) NOT NULL,
  `Password` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `FirstName` VARCHAR(50) NOT NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `Active` BIT NOT NULL,
  `IsAdmin` BIT NOT NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeinventorydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeinventorydb`.`categories` (
  `CategoryID` INT NOT NULL AUTO_INCREMENT,
  `CategoryName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeinventorydb`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeinventorydb`.`items` (
  `ItemID` INT NOT NULL AUTO_INCREMENT,
  `Category` INT NOT NULL,
  `ItemName` VARCHAR(45) NOT NULL,
  `Price` DOUBLE NOT NULL,
  `Owner` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ItemID`),
  INDEX `fk_items_Categories_idx` (`Category` ASC),
  INDEX `fk_items_users1_idx` (`Owner` ASC),
  CONSTRAINT `fk_items_Categories`
    FOREIGN KEY (`Category`)
    REFERENCES `homeinventorydb`.`categories` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_users1`
    FOREIGN KEY (`Owner`)
    REFERENCES `homeinventorydb`.`users` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `categories` (`CategoryName`) VALUES ('Tattoo Supplies');
INSERT INTO `categories` (`CategoryName`) VALUES ('Miscellaneous');

INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`IsAdmin`) VALUES ('admin','password','GoodFriendTattoo@gmail.com','Admin','Admin',1,1);
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`IsAdmin`) VALUES ('GoodFriendTattoo','password','GoodFriendTattoo@gmail.com','Admin2','Admin2',1,1);

--INSERT INTO `items` (`ItemID`, `Category`, `ItemName`, `Price`, `Owner` ) VALUES (0, 'Tattoo Supplies', 'Needles', 1, 'GoodFriendTattoo');

